index:
  path: /
  controller: App\Controller\DefaultController::index

auth:
  path: /auth
  controller: App\Controller\User\AuthController::index

logout:
  path: /logout
  methods: GET

registration:
  path: /registration
  controller: App\Controller\User\RegistrationController::index

registration_create_user:
  path: /registration/create
  controller: App\Controller\User\RegistrationController::createUser
  methods: POST

profile:
  path: /profile
  controller: App\Controller\User\PersonalAccountController::index
  methods: GET
  condition:  "context.getMethod() in ['GET', 'HEAD']"

profile_update:
  path: /profile/update
  controller: App\Controller\User\PersonalAccountController::updateProfile
  methods: POST

tasks:
  path: /tasks
  controller: App\Controller\Task\TaskController::index
  methods: GET

task_new:
  path: /tasks/new
  controller: App\Controller\Task\TaskController::newTask
  methods: GET

task_create:
  path: /tasks/new/create
  controller: App\Controller\Task\TaskController::createTask
  methods: POST